; PlatformIO Project Configuration File

[env:stm8sblue]
platform = ststm8
board = stm8sblue
framework = spl

build_flags =
    -D STM8S103
    -D USE_STDPERIPH_DRIVER
    --opt-code-size

upload_protocol = stlinkv2